# 找出今天成交量是昨天的几倍的股票

- 剔除停牌的
- 剔除一字板的
- 剔除新股
- 剔除st股
- TODO

In [1]:
import tushare as ts
dfsh = ts.get_hist_data('sh',start='2016-01-05')
date = list(dfsh.index)
[today,last] = date[0:2]
df = ts.get_today_all() 
lastData = df.loc[:,['code','name','volume']]
lastData.to_json(today+'-unicode.json',orient='records')
lastData.to_json(today+'-gbk.json',orient='records',force_ascii=False) 
df.to_json(today+'-gbk-all.json',orient='records',force_ascii=False)

[Getting data:]#####################################

In [2]:
import tushare as ts
import pandas as pd
import numpy as np
dfsh = ts.get_hist_data('sh',start='2016-01-05')
date = list(dfsh.index)
[today,last] = date[0:2]
dft = pd.read_json(today+'-gbk-all.json',orient='records', typ='frame',numpy=False) 
dfy = pd.read_json(last+'-gbk-all.json',orient='records', typ='frame',numpy=False) 
# print dft.head()
# print dft.ix[2268]
# print '-------------------------'
# print dfy.ix[2268]
# print '-------------------------'
# print dft.index
# print dft.columns
# print dft.shape
# pandas.read_json(path_or_buf=None, orient=None, typ='frame', dtype=True, convert_axes=True, 
# convert_dates=True, keep_default_dates=True, numpy=False, precise_float=False, date_unit=None)¶
# Convert a JSON string to pandas object
tdata = dft.loc[:,['code','name','volume']]
ydata = dfy.loc[:,['code','name','volume']]

tdata =  tdata.set_index(['code'])
ydata =  ydata.set_index(['code'])

# tdata.set_index(['code'])
# print tdata.set_index(['code'])['300146',:]
# print tdata.set_index(['code'])
# print tdata.set_index('code',inplace=True).index
# print tdata.set_index(['code']).index|
# print tdata.shape
# print ydata.shape
# print '-------------------------'
# print tdata.ix[2268]
# print '-------------------------' 
# print ydata.ix[2268]
# print '-------------------------'

tdata['volumeLast']=ydata['volume']
tdata['rate']= tdata['volume']/tdata['volumeLast']
tdata.columns

# print '-------------------------'
# print tdata.ix[2268]
# print '-------------------------'
alpha =1000
data = tdata[(tdata.volume>alpha) & (tdata.volumeLast>alpha) & (tdata.rate<20)].sort_values(by='rate')
data.sort_values(by='rate').to_excel('a.xls');
date  = [today,last]
print date 
print '------------------------------------------------------'
print data.head(10)
print  '\t\t\n'
print data.tail(10)
print '------------------------------------------------------'
print data[(data.rate>2) & (data.rate <5) ].head(20)
print  '\t\t\n'
print data[(data.rate>2) & (data.rate <5) ].tail(20)
print  '\t\t\n'
# data =   pd.concat({'code':tdata.loc[:,['code']], 'name':tdata.loc[:,['name']], 'AA':tdata.loc[:,['volume']],'BB':ydata.loc[:,['volume']] }, axis=1)
# data.head()
# data['rate']= data['AA']/data['BB']
# # data.reset_index(level=['code','name','AA','BB','rate'])
# data.reindex(level=['code','name','AA','BB','rate'] )
# data.sort_values(by='rate').to_excel('a.xls');
# data.columns
# data[data.AA>0]
# data[(data['volume'] > 10)]
# datasorted = data[(data.volume > 10) & (data.volume-lastday>10)].sort_values(by='rate')
# datasorted.dropna(how='any').head()
 
# datasorted.dropna(how='any').tail()
# datasorted.tail()

# def f(x):
#     return 99;
# data['rate'] = data.applymap(f).all(axis=1).astype(float)
# data.as_matrix()
# tt = np.array(data)
# data.head()
# tt

[u'2016-02-17', u'2016-02-16']
------------------------------------------------------
         name    volume  volumeLast      rate
code
155     *ST川化    795985     3481969  0.228602
2504     弘高创意   2553563     8835267  0.289019
600288   大恒科技   4379765    13362654  0.327762
600377   宁沪高速   5676456    14749111  0.384868
600283   钱江水利   5502203    13211752  0.416463
520      长航凤凰   7636885    17524888  0.435774
688      建新矿业  18318026    41149571  0.445157
603023   威帝股份   1229980     2579967  0.476743
2213    特 尔 佳   4052167     8431590  0.480593
600083   博信股份   1571808     3264987  0.481413


         name     volume  volumeLast       rate
code
601003   柳钢股份   43671715    11835068   3.690027
972       新中基   69720010    18355761   3.798263
300228   富瑞特装   23242115     5876712   3.954952
2506     协鑫集成  174548485    40804598   4.277667
2043    兔 宝 宝   72698802    16385087   4.436888
600789   鲁抗医药   64208958    12527512   5.125436
600234   山水文化   50708179     9286175   5.460610
300322    硕贝德   26504801     4367403   6.068778
600872   中炬高新   41744221     5779079   7.223335
2358     森源电气   40389066     2412373  16.742463
------------------------------------------------------
         name    volume  volumeLast      rate
code
561      烽火电子  57351772    28539757  2.009540
600648    外高桥  12594284     6263079  2.010877
600284   浦东建设  17430881     8645997  2.016064
600756   浪潮软件  37516499    18607807  2.016170
300236   上海新阳   6767563     3335687  2.028836
2772     众兴菌业   3823853     1874892  2.039506
2292     奥飞动漫  74006377    36199146  2.044423
600641   万业企业  25601837    12488966  2.049956
2302     西部建设   7348773     3578598  2.053534
600652   游久游戏  84552109    41153303  2.054564
948      南天信息  22547410    10968672  2.055619
300394   天孚通信   1833195      890286  2.059108
600365   通葡股份  32678035    15832235  2.064019
2017     东信和平  17265823     8323036  2.074462
600012   皖通高速  27019262    12984028  2.080961
600378   天科股份  22886957    10987793  2.082944
600577   精达股份  41955770    20078289  2.089609
565      渝三峡Ａ  14826163     7084008  2.092906
861      海印股份  36155885    17142783  2.109102
890     法 尔 胜  15790506     7444183  2.121187


         name      volume  volumeLast      rate
code
2431     棕榈园林    37691228    13409871  2.810708
600246   万通地产    41429112    14736267  2.811371
2586     围海股份    49449977    17308343  2.857002
600801   华新水泥    26433191     9183914  2.878205
627      天茂集团    58775406    20351413  2.888026
600161   天坛生物    12483568     4312572  2.894692
600639   浦东金桥    19263574     6559099  2.936924
725      京东方Ａ  1283140845   423328076  3.031079
300149   量子高科    39178344    12827338  3.054285
600415   小商品城   106142391    34129521  3.109988
600737   中粮屯河   112423579    35371778  3.178341
601678   滨化股份    44198850    13348579  3.311128
2104     恒宝股份    70794366    21041681  3.364482
600774   汉商集团    20928369     5897086  3.548934
300020   银江股份    43844688    12006347  3.651793
601003   柳钢股份    43671715    11835068  3.690027
972       新中基    69720010    18355761  3.798263
300228   富瑞特装    23242115     5876712  3.954952
2506     协鑫集成   174548485    40804598  4.277667
2043    兔 宝 宝    72698802    16385087  4.436888

In [28]:
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.randn(6,4),columns=list('ABCD'))
df
print df
print df[df.D>0]
print df[df.D>0.5]

          A         B         C         D
0  0.323048  1.008106 -0.729530  0.909791
1  0.114093 -0.679794 -2.992686  0.447559
2  0.274385  1.014179 -0.324960  0.038065
3 -0.012288  0.002518  0.978408  0.204245
4 -0.518606 -1.280340  1.613181 -0.690997
5  0.159412 -0.054222  0.800970 -0.731827
          A         B         C         D
0  0.323048  1.008106 -0.729530  0.909791
1  0.114093 -0.679794 -2.992686  0.447559
2  0.274385  1.014179 -0.324960  0.038065
3 -0.012288  0.002518  0.978408  0.204245
          A         B        C         D
0  0.323048  1.008106 -0.72953  0.909791